### ISSUE TITLE
Fix cache path for php images

### ISSUE THREAD

**Issue by aritomelo** [ec-europa/atomium#222]

**Comment by voidtek** [comment]
see https://webgate.ec.europa.eu/CITnet/jira/browse/OPENEUROPA-1515

**Comment by drupol** [comment]
After a discussion with @voidtek, I'm going to close this issue and the associated PR #223 

We cannot enforce users to use the cache. We should be shipping the uppermost basic docker configuration and let user customize it at will.

That said, once devOps will have their images fixed, we will add some documentation on how to enable caching because this can be very useful on Drone and locally.
